// This code was autogenerated with `dbus-codegen-rust -r --file org.freedesktop.ScreenSaver.xml`, see https://github.com/diwic/dbus-rs
use dbus as dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus_crossroads as crossroads;

pub trait OrgFreedesktopScreenSaver {
    fn inhibit(&mut self, application_name: String, reason_for_inhibit: String) -> Result<u32, dbus::MethodErr>;
    fn un_inhibit(&mut self, cookie: u32) -> Result<(), dbus::MethodErr>;
}

pub fn register_org_freedesktop_screen_saver<T>(cr: &mut crossroads::Crossroads) -> crossroads::IfaceToken<T>
where T: OrgFreedesktopScreenSaver + Send + 'static
{
    cr.register("org.freedesktop.ScreenSaver", |b| {
        b.method("Inhibit", ("application_name","reason_for_inhibit",), ("cookie",), |_, t: &mut T, (application_name,reason_for_inhibit,)| {
            t.inhibit(application_name,reason_for_inhibit,)
                .map(|x| (x,))
        });
        b.method("UnInhibit", ("cookie",), (), |_, t: &mut T, (cookie,)| {
            t.un_inhibit(cookie,)
        });
    })
}
